### PR TITLE
Migrated project to MPS 2021.3.2

### PR DESCRIPTION
**Pull request by arimer**
This PR updates all deps and builds scripts, fixes broken API and executes all migrations Provided by MPS 2021.3.2. 

I am not sure about the naming/branching schema of the target repository. Maybe it makes sense to create first a matching target branch in the original repository, before merging the PR.

### CODE REVIEW

**Comment by ftomassetti** [comment]
Thank you @arimer !

**Comment by ftomassetti** [comment]
I have copied this code in the new branch mps2021.3.2 instead of merging them into the branch [mps2021.1](https://github.com/Strumenta/MPSServer/tree/mps2021.1)

**Comment by alamqadem** [comment]
Hi @ftomassetti, is there already a package released for this version?

**Comment by ftomassetti** [comment]
hi @dodoga93 no because there is seems to be a problem with some dependencies forcing the adoption of the JVM 18, this prevent building at the moment

**Pull request closed without merging**
