### PR TITLE
migrated to MPS 2022.2

### PR DESCRIPTION
**Pull request by enikao**
except Modelix-related parts, as modelix is not available for that MPS version

3 Tests are failing atm

### CODE REVIEW

**Comment by enikao** [comment]
Maybe **don't** merge into branch `mps2020.3`, but create a new branch `mps2022.2`

**Comment by ftomassetti** [comment]
We would need to specify the new MPS version into versions.gradle

**Comment by ftomassetti** [comment]
The branch `[mps2021.1](https://github.com/Strumenta/MPSServer/tree/mps2021.1)` is more recent than mps2020.3, so maybe we could merge changes from that branch into this one

**Comment by enikao** [comment]
> The branch `[mps2021.1](https://github.com/Strumenta/MPSServer/tree/mps2021.1)` is more recent than mps2020.3, so maybe we could merge changes from that branch into this one

Oops, missed that branch! The migration was painless, so I'll do it again based on that branch.

**Comment by enikao** [comment]
Hmm, not so easy: _mps-extensions_ 2021.3 (newest release) does not work on 2022.2 (some reflection magic fails).
I think it's best to abandon this PR; I will "be inspired" by parts of MPSServer for LIonWeb MPS Server, and just salvage that part.

**Comment by ftomassetti** [comment]
Understood. I think for the sake of a demo it makes sense to just put something together (by the way, feel free to just copy anything that can be useful). If later the project is maintained and parts of MPSServer can help, we could also extract them into a component without dependencies. If that is useful please let me know, I would be happy to help

**Pull request closed without merging**
